export const BOOKMARK_SEND = 'BOOKMARK_SEND';
export const BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
export const BOOKMARK_FAIL = 'BOOKMARK_FAIL';
export const BOOKMARK_GET_ALL = 'BOOKMARK_GET_ALL';
export const BOOKMARK_GET_ALL_FAIL = 'BOOKMARK_GET_ALL_FAIL';
export const BOOKMARK_DELETE = 'BOOKMARK_DELETE';
export const BOOKMARK_DELETE_FAIL = 'BOOKMARK_DELETE_FAIL';
export const BOOKMARK_DELETE_SUCCESS = 'BOOKMARK_DELETE_SUCCESS';
