// articles
export const CREATE_ARTICLE_STARTED = 'CREATE_ARTICLE_STARTED';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';
export const CREATE_ARTICLE_FINISHED = 'CREATE_ARTICLE_FINISHED';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';
export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const RESET_ARTICLE = 'FETCH_ARTICLE_SUCCESS';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const FETCH_FEEDS_SUCCESS = 'FETCH_FEEDS_SUCCESS';
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL';
export const FETCH_ARTICLE_END = 'FETCH_ARTICLE_END';
export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const DISLIKE_ARTICLE = 'DISLIKE_ARTICLE';
export const FETCH_AGAIN_DISLIKES = 'FETCH_AGAIN_DISLIKES';
export const FETCH_AGAIN_LIKES = 'FETCH_AGAIN_LIKES';
export const LIKE_ARTICLE_FAIL = 'LIKE_ARTICLE_FAIL';
export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';
export const CLEAR_EDITOR = 'CLEAR_EDITOR';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';
export const DISLIKE_COMMENT_SUCCESS = 'DISLIKE_COMMENT_SUCCESS';
export const LIKE_COMMENT_FAIL = 'LIKE_COMMENT_FAIL';
// accounts
export const FETCH_START = 'FETCH_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS';
export const FETCH_FOLLOWERS_FAIL = 'FETCH_FOLLOWERS_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const FETCH_END = 'FETCH_USER_END';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// others
export const REDIRECT_TO = 'REDIRECT_TO';
