export const REQUEST_RESET = 'REQUEST_RESET';
export const REQUEST_RESET_SENT = 'REQUEST_RESET_SENT';
export const REQUEST_RESET_FAIL = 'REQUEST_RESET_FAIL';
export const RESETTING_PASSWORD = 'RESETTING_PASSWORD';
export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAIL = 'RESET_PASS_FAIL';
