/*
 * The action types will be imported here.
 *
 */
export const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const SIGNUP = 'USER_SIGNUP';
export const GOOGLE_SOCIAL_ACCESS_SUCCESS = 'GOOGLE_SOCIAL_ACCESS_SUCCESS';
export const GOOGLE_SOCIAL_ACCESS_FAILED = 'GOOGLE_SOCIAL_ACCESS_FAILED';
export const FACEBOOK_SOCIAL_ACCESS_SUCCESS = 'FACEBOOK_SOCIAL_ACCESS_SUCCESS';
export const FACEBOOK_SOCIAL_ACCESS_FAILED = 'FACEBOOK_SOCIAL_ACCESS_FAILED';
export const RELOAD_SOCIAL_MEDIA = 'RELOAD_SOCIAL_MEDIA';
export const USER_FOLLOW_COUNT = 'USER_FOLLOW_COUNT';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const UN_FOLLOW_FAIL = 'UN_FOLLOW_FAIL';
export const UN_FOLLOW_SUCCESS = 'UN_FOLLOW_SUCCESS';
export const USER_FOLLOWING_COUNT = 'USER_FOLLOWING_COUNT';
